# Generated by Django 4.0.6 on 2022-07-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bigimage', models.ImageField(upload_to='media/')),
                ('image', models.ImageField(upload_to='media/')),
                ('ytlink', models.URLField()),
                ('tomorrow', models.URLField()),
                ('paragraph', models.TextField(max_length=20000)),
                ('title', models.CharField(max_length=200)),
                ('released', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(max_length=200)),
                ('casts', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('production', models.CharField(max_length=200)),
            ],
        ),
    ]
