# Generated by Django 4.0.6 on 2022-07-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_movie_bigimage_alter_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='paragraph',
        ),
    ]
