# Generated by Django 4.0.6 on 2022-07-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='choice',
        ),
    ]
