# Generated by Django 4.0.6 on 2022-07-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_contact_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_persons', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
