# Generated by Django 4.0.6 on 2022-07-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
