# Generated by Django 4.0.6 on 2022-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_reservation_email_reservation_name_reservation_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reserve',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
