# Generated by Django 4.0.6 on 2022-08-02 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_movie_reserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='quantity',
        ),
        migrations.AddField(
            model_name='movie',
            name='regisor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
